"""remove_unique_constraint_from_config_key

Revision ID: 50b6494939cc
Revises: db6b542a7134
Create Date: 2025-11-03 19:17:10.794145

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50b6494939cc"
down_revision: Union[str, None] = "db6b542a7134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint from config.key
    # SQLite doesn't support dropping constraints directly, so we recreate the table

    # Create new table without unique constraint
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS config_new (
            id INTEGER NOT NULL,
            key VARCHAR NOT NULL,
            value VARCHAR NOT NULL,
            PRIMARY KEY (id)
        )
    """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_config_new_id ON config_new (id)")

    # Copy data from old table to new table
    op.execute(
        "INSERT INTO config_new (id, key, value) SELECT id, key, value FROM config"
    )

    # Drop old table
    op.execute("DROP TABLE config")

    # Rename new table to config
    op.execute("ALTER TABLE config_new RENAME TO config")

    # Recreate index with correct name
    op.execute("DROP INDEX IF EXISTS ix_config_new_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_config_id ON config (id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add unique constraint to config.key
    with op.batch_alter_table("config", schema=None, recreate="always") as batch_op:
        batch_op.create_unique_constraint("uq_config_key", ["key"])
    # ### end Alembic commands ###
