"""Change due_date to due_day

Revision ID: 85d7ba078009
Revises: 4a90da7e0db8
Create Date: 2025-05-31 13:04:55.062427

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85d7ba078009"
down_revision: Union[str, None] = "4a90da7e0db8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bills", sa.Column("due_day", sa.Integer(), nullable=False))
    op.drop_column("bills", "due_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills", sa.Column("due_date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("bills", "due_day")
    # ### end Alembic commands ###
